start:
	go run . --gRPCMockServer.protoManager.protoImportPaths=D:\Go\projects\bapis \
	--gRPCMockServer.protoManager.protoImportPaths=D:\Go\projects\bapis\third_party \
	--gRPCMockServer.protoManager.protoDir=D:\workspace\github.com\storyicon\powermock\examples\greeter\apis