// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1alpha1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// MockClient is the client API for Mock service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MockClient interface {
	SaveMockAPI(ctx context.Context, in *SaveMockAPIRequest, opts ...grpc.CallOption) (*SaveMockAPIResponse, error)
	DeleteMockAPI(ctx context.Context, in *DeleteMockAPIRequest, opts ...grpc.CallOption) (*DeleteMockAPIResponse, error)
	ListMockAPI(ctx context.Context, in *ListMockAPIRequest, opts ...grpc.CallOption) (*ListMockAPIResponse, error)
}

type mockClient struct {
	cc grpc.ClientConnInterface
}

func NewMockClient(cc grpc.ClientConnInterface) MockClient {
	return &mockClient{cc}
}

func (c *mockClient) SaveMockAPI(ctx context.Context, in *SaveMockAPIRequest, opts ...grpc.CallOption) (*SaveMockAPIResponse, error) {
	out := new(SaveMockAPIResponse)
	err := c.cc.Invoke(ctx, "/powermock.apis.v1alpha1.Mock/SaveMockAPI", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mockClient) DeleteMockAPI(ctx context.Context, in *DeleteMockAPIRequest, opts ...grpc.CallOption) (*DeleteMockAPIResponse, error) {
	out := new(DeleteMockAPIResponse)
	err := c.cc.Invoke(ctx, "/powermock.apis.v1alpha1.Mock/DeleteMockAPI", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mockClient) ListMockAPI(ctx context.Context, in *ListMockAPIRequest, opts ...grpc.CallOption) (*ListMockAPIResponse, error) {
	out := new(ListMockAPIResponse)
	err := c.cc.Invoke(ctx, "/powermock.apis.v1alpha1.Mock/ListMockAPI", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MockServer is the server API for Mock service.
// All implementations must embed UnimplementedMockServer
// for forward compatibility
type MockServer interface {
	SaveMockAPI(context.Context, *SaveMockAPIRequest) (*SaveMockAPIResponse, error)
	DeleteMockAPI(context.Context, *DeleteMockAPIRequest) (*DeleteMockAPIResponse, error)
	ListMockAPI(context.Context, *ListMockAPIRequest) (*ListMockAPIResponse, error)
	mustEmbedUnimplementedMockServer()
}

// UnimplementedMockServer must be embedded to have forward compatible implementations.
type UnimplementedMockServer struct {
}

func (*UnimplementedMockServer) SaveMockAPI(context.Context, *SaveMockAPIRequest) (*SaveMockAPIResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveMockAPI not implemented")
}
func (*UnimplementedMockServer) DeleteMockAPI(context.Context, *DeleteMockAPIRequest) (*DeleteMockAPIResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteMockAPI not implemented")
}
func (*UnimplementedMockServer) ListMockAPI(context.Context, *ListMockAPIRequest) (*ListMockAPIResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListMockAPI not implemented")
}
func (*UnimplementedMockServer) mustEmbedUnimplementedMockServer() {}

func RegisterMockServer(s *grpc.Server, srv MockServer) {
	s.RegisterService(&_Mock_serviceDesc, srv)
}

func _Mock_SaveMockAPI_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveMockAPIRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MockServer).SaveMockAPI(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/powermock.apis.v1alpha1.Mock/SaveMockAPI",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MockServer).SaveMockAPI(ctx, req.(*SaveMockAPIRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Mock_DeleteMockAPI_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteMockAPIRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MockServer).DeleteMockAPI(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/powermock.apis.v1alpha1.Mock/DeleteMockAPI",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MockServer).DeleteMockAPI(ctx, req.(*DeleteMockAPIRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Mock_ListMockAPI_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMockAPIRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MockServer).ListMockAPI(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/powermock.apis.v1alpha1.Mock/ListMockAPI",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MockServer).ListMockAPI(ctx, req.(*ListMockAPIRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Mock_serviceDesc = grpc.ServiceDesc{
	ServiceName: "powermock.apis.v1alpha1.Mock",
	HandlerType: (*MockServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SaveMockAPI",
			Handler:    _Mock_SaveMockAPI_Handler,
		},
		{
			MethodName: "DeleteMockAPI",
			Handler:    _Mock_DeleteMockAPI_Handler,
		},
		{
			MethodName: "ListMockAPI",
			Handler:    _Mock_ListMockAPI_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "apis/v1alpha1/apis.proto",
}
