name: Go

on:
    push:
        branches: [ feature/github-actions ]
    pull_request:
        branches: [ feature/github-actions ]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Golang CGO cross compiler
                # You may pin to the exact commit or the version.
                # uses: crazy-max/ghaction-xgo@0bf105240c754748ecfb954a003a7e2ad8518a4b
              uses: crazy-max/ghaction-xgo@v1.6.1
              with:
                  pkg: cmd/powermock
                  # xgo version
                  xgo_version: latest # optional, default is latest
                  # Go release to use for cross compilation
                  go_version: latest # optional, default is latest
                  # Destination folder to put binaries in
                  dest: build # optional, default is build
                  # Comma separated targets to build for. Example: windows/amd64,linux/386
                  targets: "*/*"
                  # Prints the names of packages as they are compiled
                  v: false # optional, default is false
                  # Prints the build commands as compilation progresses
                  x: false # optional, default is false
                  # Enable data race detection (supported only on amd64)
                  race: true # optional, default is false
                  # Indicates which kind of object file to build
                  buildmode: default # optional, default is default